[profile.default]
evm_version = "paris"
extra_output = [
  "storageLayout",
]
fs_permissions = [{access = "read", path = "./out"}]
libraries = [
  "./node_modules/poseidon-solidity/PoseidonT3.sol:PoseidonT3:0x0255B1FD803ffC4cD6F5b46ACb02C1fD917Db1c4",
  "./node_modules/@zk-kit/incremental-merkle-tree.sol:IncrementalBinaryTree:0x45917a20Ba9B8aA221653aA63C65059257794b19",
]
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 200
out = "out"
solc_version = "0.8.20"
src = "contracts"
test = "tests"
